Fix dir
primihub/primihub pull request #178
Opened 2022-10-31 08:29 UTC by xujiangyu

fix:
 1、os.makedir ➡️ os.mkidir
 2、xgb(plaintext) evaluation raise error

2022-10-31 10:52 UTC, hobo0cn requested changes
Please follow [PR checklist](https://github.com/primihub/primihub/blob/develop/.github/PULL_REQUEST_TEMPLATE.md). @xujiangyu

2022-11-01 05:29 UTC, LinuxSuRen requested changes

2022-11-01 05:29 UTC, LinuxSuRen commented on python/primihub/context.py
> +                    #os.makedir(output_dir)
Forget to delete this line?

2022-11-02 02:35 UTC, xujiangyu commented on python/primihub/context.py
> +                    #os.makedir(output_dir)
ok,

2022-11-02 02:45 UTC, closed without merging

2022-11-02 02:45 UTC, xujiangyu commented
I will submit it later.